---
title: "**About**"
output: 
  html_document:
    toc: true
    toc_float: true
---

###Project Motivation 

Consumer product-related injuries does not seem to be uncommon in everyday life. Annually, these product related injuries account for approximately 29% of unintentional injury deaths. We want to investigate the product-related injuries in a relatively large scale and visualize the results in a clear, understandable way for public, and provide a guideline for prevent further injuries in daily life. 

This project is also served as the final project for course [P8105 Data Science](https://p8105.com/) in 2020 fall semester. 


###Dataset 

We used data from [National Electronic Injury Surveillance System (NEISSS)](https://www.cpsc.gov/Research--Statistics/NEISS-Injury-Data/) to invistigate the risk of consumer product-related injuries occurring in the United States. NEISS is operated by United States Consumer Product Safety Commission (CPSC) who conducted the statistically valid injury surveillance for more than 45 years. 

The dataset we adopted is the NEISS data from 2013 to 2017 as "injuries", together with a product code lookup table as "products" and the population of the US by age, sex, and year as "population". The whole dataset is also available [here](https://github.com/hadley/neiss). 


###Group Members

* Lin Feng (LF2649) 
* Daniel Ojeranti (DO2381)
* Elizabeth Park (EP2899)
* Eric Sun (ES3201)
