---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r, setup, echo = F, message = FALSE, warning=FALSE}
library(tidyverse)
library(p8105.datasets)
library(hexbin)
library(rvest)
library(ggridges)
library(patchwork)
knitr::opts_chunk$set(
	fig.width = 6, 
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(0817)
```


```{r,  echo = F, message = FALSE, warning=FALSE}
data("injuries")
data("population")
data("products")
```

```{r,  echo = F, message = FALSE, warning=FALSE}
test = injuries %>% 
  select(code = prod1, everything())

new = merge(test, products, by = "code")
season.df = 
  new %>% 
  separate(trmt_date, c("year","month","day"), sep = "-") %>% 
  mutate(
    month = as.double(month),
      season = case_when(
      month %in% 9:11 ~ "Fall",
      month %in% 3:5  ~ "Spring",
      month %in% 6:8  ~ "Summer",
      TRUE ~ "Winter"))

race_head=
  injuries %>% 
     select(trmt_date, race, race_other, body_part, disposition, prod1, prod2
  ) 

neiss_df = 
  injuries %>% 
  select(trmt_date, age, sex, race, body_part, diag, disposition, prod1) %>%
  rename(code = prod1)

neiss_df = left_join(neiss_df, products, by = "code") 

prod_headdf = neiss_df %>%
  filter(body_part %in% c ("Head", "Face", "Neck",  "Ear", "Eyeball"))

```

Column {data-width=600}
-----------------------------------------------------------------------

### Head and Neck Injuries by Product 

```{r}
prod_headdf %>%
  group_by(title, diag) %>%
  summarize(total = n()) %>%
  mutate(
    title = fct_reorder(title, desc(total))) %>%
    filter(total >=5000) %>%
  ggplot(aes(x = title, y = total, fill = diag)) +
  geom_col(alpha = .5) +
  labs(x = "Product",
       y = "Number of Injuries")+
  coord_flip() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1), 
        legend.title = element_blank())

```

Column {data-width=400}
-----------------------------------------------------------------------


### Most Common Injured Body Parts by Sex

```{r}
injuries %>% 
  group_by (sex) %>% 
  count(body_part) %>% 
  arrange(desc(n)) %>% 
  mutate(
        body_part = factor(body_part),
        body_part = fct_reorder(body_part, n)
    ) %>% 
  ggplot(aes(x = body_part, y = n)) + 
  geom_point(aes(color = sex)) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))+
     labs(x="Body Part", y="N")


```

### Head Injury Requiring Admission in each Race

```{r}
race_head %>%
filter(body_part %in% c ("Head"),
        disposition == "Admitted") %>%   
  separate(trmt_date, into = c("year", "month", "day"), convert = TRUE) %>%
  select (-month, -day, -race_other, -disposition, -prod1, -prod2) %>% 
  group_by(body_part, race, year) %>% 
  count(body_part, name = "Head_Total") %>% 
  ggplot(aes(x = year, y = Head_Total, color=race)) + 
  geom_line()+
  geom_point()+
  facet_grid(~ race)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

```

