---
title: "**Report**"
output: 
  html_document:
    toc: true
    toc_float: true
---


### Project Motivation 

Consumer product-related injuries does not seem to be uncommon in everyday life. However, over 13 million people sought care in emergency departments in 2019 in the US due to these injuries. Annually, these product related injuries account for approximately 29% of unintentional injury deaths. Therefore, studying these injuries can lead to significant public health improvements. We want to investigate the product-related injuries in a relatively large scale and visualize the results in a clear, understandable way for public, and provide a guideline for prevent further injuries in daily life. 

This project is also served as the final project for course [P8105 Data Science](https://p8105.com/) in 2020 fall semester. 

#### Related work
* [Consumer Product Safety Commission](https://www.cpsc.gov/) provides up-to-date information on recalled and potentially dangerous products
* [National Safety Council](https://injuryfacts.nsc.org/home-and-community/home-and-community-overview/introduction/) provides an overview and more background on preventable injuries
* [Cost analysis](https://pubmed.ncbi.nlm.nih.gov/25084777/) demonstrates the significant cost of these injuries to the U.S. economy, almost $1 trillion per year

#### Initial questions
* Which products are associated with injury? What about severe injury?
* How are people injured by consumer products? Are there particular body parts that are injured more often or more severely?
* What differences can we find among injuries by sex, race, and other demographic factors?


### Dataset 

We used data from [National Electronic Injury Surveillance System (NEISS)](https://www.cpsc.gov/Research--Statistics/NEISS-Injury-Data/) to investigate the risk of consumer product-related injuries occurring in the United States. NEISS is operated by United States Consumer Product Safety Commission (CPSC) who conducted the statistically valid injury surveillance for more than 45 years. 

The dataset we adopted is the NEISS data from 2013 to 2017 as "injuries", together with a product code lookup table as "products" and the population of the US by age, sex, and year as "population". The whole dataset is also available [here](https://github.com/hadley/neiss). The "injuries" dataset is the primary dataset containing detailed information about each emergency department encounter such as date, age, sex, race, body part involved, and product involved. We joined the "injuries" dataset to the "products" dataset when examining the product causes of injuries.

### Exploratory Analysis

The goal of our project was to take a broad overview of product injuries which included a number of analyses where we analyzed the data by several of the variables in the dataset to identify any unusual or interesting patterns. These initial analyses included stratifying the data by sex, body part, and season. Furthermore, we wanted to understand not just the number of injuries, but also the severity of those injuries. Thus, we added on the disposition category to better distinguish between minor and severe injuries. Due to finding a low number of overall deaths due to consumer products, hospital admission was used as the main indicator of severe injury. In looking at the initial data, we found that head injuries not only made up the largest proportion of injuries by body part, but that they also tended to be more severe, oftentimes leading to admissions. Therefore, we drilled down further into the category of head/neck injuries including head, face, ear, eyeball, and neck injuries to better understand the products behind those injuries and any potential disparities we could find among race/ethnicity.

### Discussion
We found a number of interesting and counterintuitive insights upon looking at the data. 

1. **Head injuries were both the most common body part involved and the most likely to lead to hospital admission.** This finding surprised us at first because we would have expected extremities such as hands or arms to be most injured by consumer products. However, considering that the database consists of visits to emergency departments, it would make sense that people would be more likely to seek hospital care due to a head injury than an extremity injury if they could treat it at home. 

    a. *House furniture and fixtures were most likely to be involved in head/neck injuries.* After examining the head/neck data by product, we found that the most common products to cause injuries overall, floors, beds, and stairs, were also the most common products here. In addition, the high number of bathtub and toilet head injuries leading to hospital admission also highlights the importance of taking precautions to avoid possible falls or other head injuries in the bathroom.

    b. *Helmet-wearing is very important for preventing serious head/neck injuries.* Bicycles were shown to cause a higher proportion of serious injuries requiring hospital admission despite causing slightly lower overall head/neck injuries, reinforcing the importance of helmet wearing when bike riding.

2. **Missing race data prevents making strong conclusions about race/ethnicity disparities in consumer product injuries.** When stratifying the data by race/ethnicity, unfortunately we found a large and increasing amount of missing race data over time. Capturing that information in the database will be important for future research purposes to help with targeting specific communities that may be disproportionately impacted by consumer injuries for public health interventions.

3. **Significant differences between men and women in product injuries exist, although overall men are injured more often.** In examining the data by sex, we found a number of interesting differences between men and women in their overall patterns of injury. For example, when examining age, men overall had higher numbers of consumer product injuries at younger ages, which then declined across age to where women had more injuries at the older extreme of age.

    a. *While both men and women had mostly head and face injuries, men report greater finger injuries while women report greater lower trunk injuries.* The difference appears to be linked to greater knife, basketball, and door finger injuries in men, while women report lower trunk injuries due to floors, stairs, and beds. 

4. **Warmer weather is associated with greater injuries.** Our analysis of the data shows that the spring and summer months are associated with greater injuries, perhaps not surprisingly as people tend to be more active. 

5. **Consumer product deaths are low overall.** When examining deaths associated with consumer products, the numbers were very low overall compared to the total. As expected, the main products were floors, beds, and stairs which were associated with higher overall injuries.  However, the next most common findings were fire, bicycles, and exercise equipment. These findings indicate the importance of proper public health messaging with regard to fire safety, helmet wearing, and safe exercise to reduce these rare but tragically preventable deaths.