---
title: "**Exploring Injuries by Season**"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r, setup, echo = F, message = FALSE, warning=FALSE}
library(tidyverse)
library(p8105.datasets)
library(hexbin)
library(rvest)
library(ggridges)
library(patchwork)
knitr::opts_chunk$set(
	fig.width = 6, 
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(0817)
```


```{r, include=FALSE}
data("injuries")
data("population")
data("products")

head(population)
head(injuries)
head(products)
```

```{r, echo = F, message = FALSE, warning=FALSE}
test = injuries %>% 
  select(code = prod1, everything())

new = merge(test, products, by = "code")
season.df = 
  new %>% 
  separate(trmt_date, c("year","month","day"), sep = "-") %>% 
  mutate(
    month = as.double(month),
      season = case_when(
      month %in% 9:11 ~ "Fall",
      month %in% 3:5  ~ "Spring",
      month %in% 6:8  ~ "Summer",
      TRUE ~ "Winter"))

```

# Seasons corresponding to the number of cases
```{r, echo = F, message = FALSE}
season.df %>% 
  count(season) %>% 
  arrange(desc(n)) %>% 
  knitr::kable()
```

# Injuries cases with 30 or more deaths

```{r, echo = F, message = FALSE}
season.df %>%
  filter(disposition == "Died") %>% 
  count(title) %>% 
  arrange(desc(n)) %>% 
  filter(n > 30) %>% 
  mutate(
		title = factor(title),
		title = fct_reorder(title, n)) %>% 
  rename("number of deaths"  = n ) %>% 
  	knitr::kable()

```

# Injuries By Seasons

## Winter

```{r, echo = F, message = FALSE}
season.df %>%
  filter(season == "Winter") %>% 
  count(body_part) %>% 
  arrange(desc(n)) %>% 
  mutate(
		body_part = factor(body_part),
		body_part = fct_reorder(body_part, n)
	) %>% 
  knitr::kable()
```

## Spring

```{r, echo = F, message = FALSE}
  season.df %>%
  filter(season == "Spring") %>% 
  count(body_part) %>% 
  arrange(desc(n)) %>% 
  mutate(
		body_part = factor(body_part),
		body_part = fct_reorder(body_part, n)
	) %>% 
  knitr::kable()
```

## Summer

```{r, echo = F, message = FALSE}
  season.df %>%
  filter(season == "Summer") %>% 
  count(body_part) %>% 
  arrange(desc(n)) %>% 
  mutate(
		body_part = factor(body_part),
		body_part = fct_reorder(body_part, n)
	) %>% 
  knitr::kable()
```


## Fall

```{r, echo = F, message = FALSE}                                                                                                                                                                                                                                                    
season.df %>%
  filter(season == "Fall") %>% 
  count(body_part) %>% 
  arrange(desc(n)) %>% 
  mutate(
		body_part = factor(body_part),
		body_part = fct_reorder(body_part, n)
	) %>% 
  knitr::kable()
```




